apiVersion: v1
kind: Namespace
metadata:
  name: dev1
  labels:
    name: dev1
---
apiVersion: sjs.gdace829/v1
kind: ElasticWeb
metadata:
  namespace: dev1
  name: elasticweb-sample
spec:
  # Add fields here
  image: tomcat:8.0.18-jre8
  port: 30003
  singlePodQPS: 500
  totalQPS: 1501
